PHC-463 Select aria-describedby
lifeomic/chroma-react pull request #57
Opened 2021-01-26 20:08 UTC by HaleyWardo

**Changes**
- Removed `aria-describeby` 
    - Was getting accessibility error because a target for the reference doesn't exist. I checked with @ynotdraw and he said it could have just been a copy/paste and that it is okay to remove.

![Screen Shot 2021-01-26 at 2 59 16 PM](https://user-images.githubusercontent.com/32574227/105898987-15ef7c80-5fe8-11eb-88c5-27f696b2427b.png)

2021-01-26 20:25 UTC, ynotdraw commented on src/components/Select/Select.tsx
> -        aria-describedby={buildDescribedBy(uniqueId)}
Actually, I believe this is used for the help/error messages.  Let's see if we can conditionally apply this attribute, if/when we do have a help or error message?

2021-01-26 20:57 UTC, ynotdraw requested changes
Will pair on changes mentioned in comment! I think conditionally applying this should work. We may also need to do it for other form elements. Nice find!

2021-01-27 16:02 UTC, ynotdraw commented
FWIW, just verified with Haley that these changes work with a screenreader 👍

2021-01-27 16:10 UTC, ynotdraw approved these changes
🙇

2021-01-27 16:10 UTC, ynotdraw commented on src/components/TextField/TextField.test.tsx
> +  expect(textfield.getAttribute('aria-describedby')).toBeFalsy();
These are a bit redundant as we have the other tests, but that's okay.

2021-01-27 18:23 UTC, dexterca approved these changes

2021-01-27 19:05 UTC, simons5593 approved these changes

2021-01-27 20:51 UTC, merged